name: flutter_webview_plugin
description: Plugin that allow Flutter to communicate with a native Webview.
homepage: https://github.com/dart-flitter/flutter_webview_plugin
version: 0.3.11
maintainer: Rafal Wachol (@RafalWachol) 

environment:
  sdk: ">=2.15.1 <3.0.0"

flutter:
  plugin:
    androidPackage: com.flutter_webview_plugin
    pluginClass: FlutterWebviewPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.17 
  flutter_test:
    sdk: flutter
